### ISSUE TITLE
`Wrapper#accept` might be crashing in production.

### ISSUE THREAD

**Issue by ioquatix** [socketry/io-endpoint#9]
https://github.com/socketry/io-endpoint/blob/e82badc71d9f2e7e51af727f4a2a27976d094396/lib/io/endpoint/wrapper.rb#L157

```
    1m     warn: Async::Task [oid=0xdfc] [ec=0xde8] [pid=56009] [2024-05-08 20:40:28 +1200]
               | Task may have ended with unhandled exception.
               |   OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 peeraddr=[::1]:50598 state=error: ssl/tls alert certificate unknown
               |   → /home/samuel/.rubies/ruby-3.3.1/lib/ruby/3.3.0/openssl/ssl.rb:527 in `accept'
               |     /home/samuel/.rubies/ruby-3.3.1/lib/ruby/3.3.0/openssl/ssl.rb:527 in `accept'
               |     /home/samuel/.gem/ruby/3.3.1/gems/io-endpoint-0.10.2/lib/io/endpoint/wrapper.rb:157 in `accept'
               |     /home/samuel/.gem/ruby/3.3.1/gems/io-endpoint-0.10.2/lib/io/endpoint/generic.rb:83 in `block in accept'
               |     /home/samuel/.gem/ruby/3.3.1/gems/io-endpoint-0.10.2/lib/io/endpoint/bound_endpoint.rb:65 in `block (2 levels) in bind'
               |     /home/samuel/.gem/ruby/3.3.1/gems/async-2.11.0/lib/async/task.rb:164 in `block in run'
               |     /home/samuel/.gem/ruby/3.3.1/gems/async-2.11.0/lib/async/task.rb:377 in `block in schedule'
```

1. Need to investigate whether SSLSocket#accept is performing additional TLS negotiation (is it causing latency in the accept loop?)
2. Need to figure out the best way to rescue errors to avoid killing the accept loop.

**Comment by ioquatix** [comment]
https://github.com/socketry/io-endpoint/pull/10

**Comment by paddor** [comment]
I have similar log entries in production, probably because customer accesses app via a different hostname than the SAN-entry in their home-rolled certificate states:

```
[2026-02-19T08:14:36.971+01:00] WARN  COMM.WEBUI                Task may have ended with unhandled exception.
OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 peeraddr=10.170.18.41:54233 state=error: sslv3 alert certificate unknown (SSL alert number 46), Backtrace:
        /snap/myapp/x49/app/vendor/bundle/ruby/4.0.0/gems/io-endpoint-0.17.2/lib/io/endpoint/ssl_endpoint.rb:20:in 'OpenSSL::SSL::SSLSocket#accept'
        /snap/myapp/x49/app/vendor/bundle/ruby/4.0.0/gems/io-endpoint-0.17.2/lib/io/endpoint/ssl_endpoint.rb:20:in 'OpenSSL::SSL::SSLSocket#start'
        /snap/myapp/x49/app/vendor/bundle/ruby/4.0.0/gems/io-endpoint-0.17.2/lib/io/endpoint/wrapper.rb:221:in 'block (2 levels) in IO::Endpoint::Wrapper#accept'
        /snap/myapp/x49/app/vendor/bundle/ruby/4.0.0/gems/async-2.36.0/lib/async/task.rb:234:in 'block in Async::Task#run'
        /snap/myapp/x49/app/vendor/bundle/ruby/4.0.0/gems/async-2.36.0/lib/async/task.rb:512:in 'block in Async::Task#schedule'
[2026-02-19T08:14:36.972+01:00] WARN  COMM.WEBUI                Task may have ended with unhandled exception.
OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 peeraddr=10.170.18.41:54234 state=error: sslv3 alert certificate unknown (SSL alert number 46), Backtrace:
        /snap/myapp/x49/app/vendor/bundle/ruby/4.0.0/gems/io-endpoint-0.17.2/lib/io/endpoint/ssl_endpoint.rb:20:in 'OpenSSL::SSL::SSLSocket#accept'
        /snap/myapp/x49/app/vendor/bundle/ruby/4.0.0/gems/io-endpoint-0.17.2/lib/io/endpoint/ssl_endpoint.rb:20:in 'OpenSSL::SSL::SSLSocket#start'
        /snap/myapp/x49/app/vendor/bundle/ruby/4.0.0/gems/io-endpoint-0.17.2/lib/io/endpoint/wrapper.rb:221:in 'block (2 levels) in IO::Endpoint::Wrapper#accept'
        /snap/myapp/x49/app/vendor/bundle/ruby/4.0.0/gems/async-2.36.0/lib/async/task.rb:234:in 'block in Async::Task#run'
        /snap/myapp/x49/app/vendor/bundle/ruby/4.0.0/gems/async-2.36.0/lib/async/task.rb:512:in 'block in Async::Task#schedule'
```
This is nothing new and doesn't seem to have any bad side effects though. The accept loop isn't killed.

**Comment by ioquatix** [comment]
Negotiating TLS is a blocking I/O bound operation and it happens in the child fiber otherwise we'd block the accept loop. This crash means the client failed to negotiate TLS, and the child fiber that accepted the connection has failed. This looks normal. Thanks for the update.
